# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./md-generator
      env:
        GEN_GITHUB_TOKEN: ${{ secrets.GEN_GITHUB_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r requirements.txt
        python main.py
    - name: Commit Readme
      working-directory: ./md-generator
      run: |
        git config --global user.name 'Stefan Witschel'
        git config --global user.email 'switschel@users.noreply.github.com'
        git commit -am "Automated Open-Source README.md"
        git push
